# Generated by Django 5.0.3 on 2025-04-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='collectioncard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collectioncard',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wantedcard',
            name='wanted',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionCard',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
        migrations.DeleteModel(
            name='Wanted',
        ),
        migrations.DeleteModel(
            name='WantedCard',
        ),
    ]
