# Generated by Django 5.0.3 on 2025-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collectioncard_date_added_wantedcard_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
