# Generated by Django 5.0.3 on 2025-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mycard_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycard',
            name='loyalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='toughness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
